
const badwords = () => {
  const filipinoBadWords = [
    'pota',
    'putang',
    'tangina',
    'tang',
    'gago',
    'bobo',
    'tanga',
    'ulol',
    'hayop',
    'lintik',
    'tarantado',
    'punyeta',
    'siraulo',
    'leche',
    'bwisit',
    'hindot',
    'inutil',
    'demonyo',
    'pakshet',
    'kantot',
    'puta',
    'shet',
    'shit',
    'tae',
    'ulol',
    'pakyu',
    'fuck',
    'fuck you',
    'kupal',
    'etits',
    'tite',
    'bobo ka',
    'bobo mo',
    'tanga ka',
    'tanga mo',
    'uto-uto',
    'gaga',
    'gagi',
    'gago ka',
    'gago mo',
    'pokpok',
    'kabet',
    'sipsip',
    'yawa',
    'hindot ka',
    'hindot mo',
    'amputa',
    'amputa ka',
    'amputa mo',
    'ulul',
    'pwe',
    'shunga',
    'shunga ka',
    'shunga mo',
    'tae ka',
    'tae mo',
    'burat',
    'burat ka',
    'burat mo',
    'puñeta',
    'puñeta ka',
    'puñeta mo',
    'bobo talaga',
    'tangina mo',
    'tangina talaga',
    'putangina mo',
    'putangina talaga',
    'ampota',
    'ampota ka',
    'ampota mo',
    'ampotangina',
    'ampotangina ka',
    'ampotangina mo',
    'puke',
    'betlog',
    'suso',
    'puday',    
    'bayag',    
    'pekpek',    
    'iyot',    
    'kantutan',    
    'pepe',    
    'ina',    
    'shabu',    
    'marijuana',    
    'chongke',
    'fb',
    'facebook',
    'number',
    'phone',    
    'kantutin',    
    'iyotin',
    'fingerin',    
    'lamas',    
    'lamasin',    
    'dilaan', 
    'supot',   
    'droga',   
    'hayup',   
    'rape',    
    'kinantot',    
    'titi',    
    'sabog',    
    'tinggel',    
    'adiik',    
    'bilat',    
    'mamatay',    
    'pakamatay',    
  ];

  return {filipinoBadWords};
}

export default badwords
